package graphics.scenery.jopenvr;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class HmdQuaternion_t extends Structure<HmdQuaternion_t, HmdQuaternion_t.ByValue, HmdQuaternion_t.ByReference > {
	public double w;
	public double x;
	public double y;
	public double z;
	public HmdQuaternion_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("w", "x", "y", "z");
	}
	public HmdQuaternion_t(double w, double x, double y, double z) {
		super();
		this.w = w;
		this.x = x;
		this.y = y;
		this.z = z;
	}
	public HmdQuaternion_t(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected HmdQuaternion_t newInstance() { return new HmdQuaternion_t(); }
	public static HmdQuaternion_t[] newArray(int arrayLength) {
		return Structure.newArray(HmdQuaternion_t.class, arrayLength);
	}
	public static class ByReference extends HmdQuaternion_t implements Structure.ByReference {
		
	};
	public static class ByValue extends HmdQuaternion_t implements Structure.ByValue {
		
	};
}
