package graphics.scenery.jopenvr;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class HmdVector4_t extends Structure<HmdVector4_t, HmdVector4_t.ByValue, HmdVector4_t.ByReference > {
	/** float[4] */
	public float[] v = new float[4];
	public HmdVector4_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("v");
	}
	public HmdVector4_t(float v[]) {
		super();
		if ((v.length != this.v.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.v = v;
	}
	public HmdVector4_t(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected HmdVector4_t newInstance() { return new HmdVector4_t(); }
	public static HmdVector4_t[] newArray(int arrayLength) {
		return Structure.newArray(HmdVector4_t.class, arrayLength);
	}
	public static class ByReference extends HmdVector4_t implements Structure.ByReference {
		
	};
	public static class ByValue extends HmdVector4_t implements Structure.ByValue {
		
	};
}
