package graphics.scenery.jopenvr;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class RenderModel_ComponentState_t extends Structure<RenderModel_ComponentState_t, RenderModel_ComponentState_t.ByValue, RenderModel_ComponentState_t.ByReference > {
	public HmdMatrix34_t mTrackingToComponentRenderModel;
	public HmdMatrix34_t mTrackingToComponentLocal;
	public int uProperties;
	public RenderModel_ComponentState_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("mTrackingToComponentRenderModel", "mTrackingToComponentLocal", "uProperties");
	}
	public RenderModel_ComponentState_t(HmdMatrix34_t mTrackingToComponentRenderModel, HmdMatrix34_t mTrackingToComponentLocal, int uProperties) {
		super();
		this.mTrackingToComponentRenderModel = mTrackingToComponentRenderModel;
		this.mTrackingToComponentLocal = mTrackingToComponentLocal;
		this.uProperties = uProperties;
	}
	public RenderModel_ComponentState_t(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected RenderModel_ComponentState_t newInstance() { return new RenderModel_ComponentState_t(); }
	public static RenderModel_ComponentState_t[] newArray(int arrayLength) {
		return Structure.newArray(RenderModel_ComponentState_t.class, arrayLength);
	}
	public static class ByReference extends RenderModel_ComponentState_t implements Structure.ByReference {
		
	};
	public static class ByValue extends RenderModel_ComponentState_t implements Structure.ByValue {
		
	};
}
