package graphics.scenery.jopenvr;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Texture_t extends Structure<Texture_t, Texture_t.ByValue, Texture_t.ByReference > {
	/** void * */
	public Pointer handle;
	/** @see ETextureType */
	public int eType;
	/** @see EColorSpace */
	public int eColorSpace;
	public Texture_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("handle", "eType", "eColorSpace");
	}
	public Texture_t(Pointer handle, int eType, int eColorSpace) {
		super();
		this.handle = handle;
		this.eType = eType;
		this.eColorSpace = eColorSpace;
	}
	public Texture_t(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected Texture_t newInstance() { return new Texture_t(); }
	public static Texture_t[] newArray(int arrayLength) {
		return Structure.newArray(Texture_t.class, arrayLength);
	}
	public static class ByReference extends Texture_t implements Structure.ByReference {
		
	};
	public static class ByValue extends Texture_t implements Structure.ByValue {
		
	};
}
