package graphics.scenery.jopenvr;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VREvent_MessageOverlay_t extends Structure<VREvent_MessageOverlay_t, VREvent_MessageOverlay_t.ByValue, VREvent_MessageOverlay_t.ByReference > {
	public int unVRMessageOverlayResponse;
	public VREvent_MessageOverlay_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("unVRMessageOverlayResponse");
	}
	public VREvent_MessageOverlay_t(int unVRMessageOverlayResponse) {
		super();
		this.unVRMessageOverlayResponse = unVRMessageOverlayResponse;
	}
	public VREvent_MessageOverlay_t(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected VREvent_MessageOverlay_t newInstance() { return new VREvent_MessageOverlay_t(); }
	public static VREvent_MessageOverlay_t[] newArray(int arrayLength) {
		return Structure.newArray(VREvent_MessageOverlay_t.class, arrayLength);
	}
	public static class ByReference extends VREvent_MessageOverlay_t implements Structure.ByReference {
		
	};
	public static class ByValue extends VREvent_MessageOverlay_t implements Structure.ByValue {
		
	};
}
