package graphics.scenery.jopenvr;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VREvent_ScreenshotProgress_t extends Structure<VREvent_ScreenshotProgress_t, VREvent_ScreenshotProgress_t.ByValue, VREvent_ScreenshotProgress_t.ByReference > {
	public float progress;
	public VREvent_ScreenshotProgress_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("progress");
	}
	public VREvent_ScreenshotProgress_t(float progress) {
		super();
		this.progress = progress;
	}
	public VREvent_ScreenshotProgress_t(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected VREvent_ScreenshotProgress_t newInstance() { return new VREvent_ScreenshotProgress_t(); }
	public static VREvent_ScreenshotProgress_t[] newArray(int arrayLength) {
		return Structure.newArray(VREvent_ScreenshotProgress_t.class, arrayLength);
	}
	public static class ByReference extends VREvent_ScreenshotProgress_t implements Structure.ByReference {
		
	};
	public static class ByValue extends VREvent_ScreenshotProgress_t implements Structure.ByValue {
		
	};
}
