package graphics.scenery.jopenvr;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VREvent_Process_t extends Structure<VREvent_Process_t, VREvent_Process_t.ByValue, VREvent_Process_t.ByReference > {
	public int pid;
	public int oldPid;
	public byte bForced;
	public VREvent_Process_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("pid", "oldPid", "bForced");
	}
	public VREvent_Process_t(int pid, int oldPid, byte bForced) {
		super();
		this.pid = pid;
		this.oldPid = oldPid;
		this.bForced = bForced;
	}
	public VREvent_Process_t(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected VREvent_Process_t newInstance() { return new VREvent_Process_t(); }
	public static VREvent_Process_t[] newArray(int arrayLength) {
		return Structure.newArray(VREvent_Process_t.class, arrayLength);
	}
	public static class ByReference extends VREvent_Process_t implements Structure.ByReference {
		
	};
	public static class ByValue extends VREvent_Process_t implements Structure.ByValue {
		
	};
}
