package graphics.scenery.jopenvr;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VREvent_Chaperone_t extends Structure<VREvent_Chaperone_t, VREvent_Chaperone_t.ByValue, VREvent_Chaperone_t.ByReference > {
	public long m_nPreviousUniverse;
	public long m_nCurrentUniverse;
	public VREvent_Chaperone_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("m_nPreviousUniverse", "m_nCurrentUniverse");
	}
	public VREvent_Chaperone_t(long m_nPreviousUniverse, long m_nCurrentUniverse) {
		super();
		this.m_nPreviousUniverse = m_nPreviousUniverse;
		this.m_nCurrentUniverse = m_nCurrentUniverse;
	}
	public VREvent_Chaperone_t(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected VREvent_Chaperone_t newInstance() { return new VREvent_Chaperone_t(); }
	public static VREvent_Chaperone_t[] newArray(int arrayLength) {
		return Structure.newArray(VREvent_Chaperone_t.class, arrayLength);
	}
	public static class ByReference extends VREvent_Chaperone_t implements Structure.ByReference {
		
	};
	public static class ByValue extends VREvent_Chaperone_t implements Structure.ByValue {
		
	};
}
